In [1]:
import itertools
from opencage.geocoder import OpenCageGeocode
from bs4 import BeautifulSoup as bs
import numpy as np
from selenium import webdriver
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from splinter import Browser
import pandas as pd
import os
import time
import requests
import warnings
warnings.filterwarnings('ignore')

In [5]:
url = "https://aviation-safety.net/statistics/geographical/worst_geo_loc.php"

driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get(url)
html = driver.page_source
a_tables = pd.read_html(html)
accidents = a_tables[0]

driver.close()

[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/Users/tylerbrown/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache

In [4]:
accidents

     #         country  accidents  fatalities  ground fat.
0    1             USA        860       10820          133
1    2          Russia        530        8418           25
2    3          Canada        191        1800            2
3    4          Brazil        189        2724           68
4    5        Colombia        183        2932           28
5    6            U.K.        110        1298           11
6    7          France        105        2247           15
7    8       Indonesia        104        2301           52
8    9          Mexico        101        1277           52
9   10           India         95        2352           27
10  11           China         75        1743           56
11  12       Venezuela         69        1119           71
12  13           Italy         68        1310            6
13  14         Ukraine         64        1338            9
14  15      D.R. Congo         64         719           77
15  16         Bolivia         62         644           88
16  17            Peru         61        1345            5
17  18         Germany         61         939            1
18  19     Philippines         61         875            7
19  20           Spain         55        2357            0
20  21       Australia         51         398            0
21  22  Atlantic Ocean         50        1203            0
22  23     P.N. Guinea         49         368            2
23  24      Kazakhstan         44         742            0
24  25       Argentina         43         819            3